version: "3.9"

services:
  python-generator:
    image: educg11/python-generator:latest
    volumes:
      - ./data:/data
    command: ["python", "script.py"]

  r-cleaner:
    image: educg11/r-cleaner:latest
    volumes:
      - ./data:/app/data
    depends_on:
      - python-generator

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
    ports:
      - "3000:3000"
    volumes:
      - ./data:/var/lib/grafana/dashboards
    depends_on:
      - r-cleaner

  git-clone:
    image: alpine/git
    volumes:
      - ./PI:/repo
    command: ["git", "clone", "https://github.com/CarlosEducg11/jenkins-web-pipeline.git", "/repo"]
    depends_on:
      - python-generator

  jenkins:
    image: custom-jenkins:latest  # or jenkins/jenkins:lts if you don’t build a custom image
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    group_add:
      - ${DOCKER_GID}  # Docker group ID passed via environment variable
    environment:
      - DOCKER_GID=965  # Replace 103 with the actual GID of your docker socket group on host
    restart: unless-stopped

volumes:
  jenkins_home: