version: '3.8'

services:
  jenkins:
    build:
      context: .
      args:
        DOCKER_GID: 999 # or get dynamically
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./entrypoint.sh:/entrypoint.sh   # mount the script inside the container root
    entrypoint: ["/entrypoint.sh"]       # full path in container
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  jenkins_home: