version: "3.9"

services:
  r-cleaner:
    image: educg11/r-cleaner:latest
    depends_on:
      - db
    environment:
      DB_HOST: db
      MYSQL_DATABASE: app_db
      MYSQL_USER: projeto
      MYSQL_PASSWORD: projeto

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: projeto
      MYSQL_PASSWORD: projeto
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  db_data: