version: "3.9"

services:
  r-cleaner:
    image: educg11/r-cleaner:latest
    volumes:
      - ./data:/app/data
    depends_on:
      - python-generator

  python-generator:
    image: educg11/python-generator:latest
    volumes:
      - ./data:/app/data
    command: ["python", "script.py"]

  dash-app:
    build: ./dash-app
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data
    depends_on:
      - r-cleaner
    command: python3 dash_app.py 
      
volumes:
  db_data: