version: "3.9"

services:
  python-generator:
    image: educg11/python-generator:latest
    command: ["python", "script.py"]
    volumes:
      - ./data:/app/data

  r-cleaner:
    image: educg11/r-cleaner:latest
    volumes:
      - ./data:/app/data
    depends_on:
      - python-generator
      
  git-clone:
    image: alpine/git
    volumes:
      - ./PI:/repo
    command: ["git", "clone", "https://github.com/CarlosEducg11/jenkins-web-pipeline.git", "/repo"]
    depends_on:
      - python-generator

volumes:
  db_data: