version: "3.9"

services:
  python-generator:
    image: educg11/python-generator:latest
    volumes:
      - ./data:/data
    command: ["python", "script.py"]

  r-cleaner:
    image: educg11/r-cleaner:latest
    volumes:
      - ./data:/app/data
    depends_on:
      - python-generator

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: projeto
      MYSQL_PASSWORD: projeto
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana          # persistence
      - ./grafana/provisioning:/etc/grafana/provisioning  # provisioning files
      - ./grafana/dashboards:/var/lib/grafana/dashboards  # dashboard JSON files
    depends_on:
      - r-cleaner

  git-clone:
    image: alpine/git
    volumes:
      - ./PI:/repo
    command: ["git", "clone", "https://github.com/CarlosEducg11/jenkins-web-pipeline.git", "/repo"]
    depends_on:
      - python-generator

volumes:
  db_data: