{
 "title": "Dashboard de Métricas DevOps",
 "tags": [
  "devops",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Duração do Job Python Generator",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "job_duration_seconds{job='python_generator'}"
    }
   ]
  },
  {
   "title": "Uso de CPU do Contêiner (Ex: dash-app)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service='dash-app'}[1m])) by (container_label_com_docker_compose_service) * 100"
    }
   ]
  },
  {
   "title": "Memória Usada do Contêiner (Ex: dash-app)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service='dash-app'}"
    }
   ]
  }
 ]
}